# Clase 06: Introducción a Pandas 🐼
### *Bootcamp Data Science 2026*

**Pandas** es la librería pilar de Python para la manipulación y análisis de datos tabulares (tablas tipo Excel). 

Hoy veremos cómo Pandas nos permite leer y analizar grandes volúmenes de datos de forma rápida gracias a la **vectorización**.

---

## 1. Estructuras de Datos de Pandas
Pandas se basa en dos componentes principales:
1. **Series**: Una columna de datos (unidimensional).
2. **DataFrame**: Una tabla completa compuesta por varias Series (bidimensional).

In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pandas in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Usuario\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
print("¡Pandas importado correctamente!")

¡Pandas importado correctamente!

### Crear un DataFrame desde cero (usando un diccionario)

In [2]:
# Ejemplo simple con estudiantes
datos_estudiantes = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana'],
    'Edad': [23, 25, 22, 28],
    'Ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'Nota_Final': [4.5, 4.8, 3.8, 4.2]
}

df = pd.DataFrame(datos_estudiantes)
df

  Nombre  Edad    Ciudad  Nota_Final
0   Juan    23    Bogotá         4.5
1  María    25  Medellín         4.8
2  Pedro    22      Cali         3.8
3    Ana    28    Bogotá         4.2

--- 
## 2. Carga de Datos y Exploración Inicial
En el mundo real cargamos datos desde archivos externos (CSV, Excel, bases de datos). Vamos a simular la carga y exploración de un archivo.

In [23]:
## Leer archivos CSV desde una ruta especifica
datos_clase = pd.read_csv(r"C:\Users\Usuario\Downloads\ventas_videojuegos.csv")
display(datos_clase.head())  ## Visualizacion del dataframe

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
1,2,CyberQuest,Xbox,Norteamerica,50,12
2,3,Galactic Combat,PC,Europa,40,45
3,4,Race King,Nintendo Switch,Asia,30,8
4,5,Fantasy RPG,PS5,Latinoamerica,70,30

In [27]:
# 0. Cargamos el dataset de ejemplo para la clase
df_ventas = pd.read_csv('ventas_videojuegos.csv')

# 1.1 Ver las primeras filas
display(df_ventas.head())

# 1.2 Ver las últimas filas
display(df_ventas.tail())

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
1,2,CyberQuest,Xbox,Norteamerica,50,12
2,3,Galactic Combat,PC,Europa,40,45
3,4,Race King,Nintendo Switch,Asia,30,8
4,5,Fantasy RPG,PS5,Latinoamerica,70,30

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
15,16,Soccer Stars 2026,Nintendo Switch,Norteamerica,60,9
16,17,CyberQuest,PS5,Latinoamerica,50,28
17,18,Galactic Combat,Xbox,Europa,40,11
18,19,Race King,PC,Asia,30,4
19,20,Fantasy RPG,Nintendo Switch,Latinoamerica,70,15

In [28]:
# 2. Diagnóstico del tipo de datos y nulos
df_ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_Venta           20 non-null     int64
 1   Videojuego         20 non-null     str
 2   Plataforma         20 non-null     str
 3   Region             20 non-null     str
 4   Precio_Unitario    20 non-null     int64
 5   Unidades_Vendidas  20 non-null     int64
dtypes: int64(3), str(3)
memory usage: 1.6 KB

In [5]:
# 3. Estadísticas descriptivas rápidas de las columnas numéricas
df_ventas.describe()

       ID_Venta  Precio_Unitario  Unidades_Vendidas
count  20.00000        20.000000          20.000000
mean   10.50000        50.000000          19.900000
std     5.91608        14.509525          14.044666
min     1.00000        30.000000           2.000000
25%     5.75000        40.000000           9.750000
50%    10.50000        50.000000          15.000000
75%    15.25000        60.000000          28.500000
max    20.00000        70.000000          50.000000

--- 
## 3. Filtros y Selección (Preguntarle a los Datos)
### A. Seleccionar Columnas

In [6]:
# Seleccionar una sola columna (obtenemos una Serie)
df_ventas['Videojuego'].head()

0    Soccer Stars 2026
1           CyberQuest
2      Galactic Combat
3            Race King
4          Fantasy RPG
Name: Videojuego, dtype: str

In [7]:
# Seleccionar múltiples columnas (pasamos una lista dentro de los corchetes)
columnas_interes = ['Videojuego', 'Plataforma', 'Unidades_Vendidas']
df_ventas[columnas_interes].head()

          Videojuego       Plataforma  Unidades_Vendidas
0  Soccer Stars 2026              PS5                 25
1         CyberQuest             Xbox                 12
2    Galactic Combat               PC                 45
3          Race King  Nintendo Switch                  8
4        Fantasy RPG              PS5                 30

### B. Filtrar Filas con Máscaras Booleanas (Paso a Paso)
Queremos ver solo las ventas donde se vendieron más de 20 unidades.

In [35]:
df_ventas.head()

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
1,2,CyberQuest,Xbox,Norteamerica,50,12
2,3,Galactic Combat,PC,Europa,40,45
3,4,Race King,Nintendo Switch,Asia,30,8
4,5,Fantasy RPG,PS5,Latinoamerica,70,30

In [36]:
# Paso 1: Crear la condición (devuelve True o False por cada fila)
condicion = df_ventas['Unidades_Vendidas'] <= 20
condicion.head()

0    False
1     True
2    False
3     True
4    False
Name: Unidades_Vendidas, dtype: bool

In [37]:
# Paso 2: Pasar esa condición al DataFrame original
df_grandes_ventas = df_ventas[condicion]
df_grandes_ventas

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
1,2,CyberQuest,Xbox,Norteamerica,50,12
3,4,Race King,Nintendo Switch,Asia,30,8
5,6,Soccer Stars 2026,Xbox,Europa,60,15
6,7,CyberQuest,PC,Latinoamerica,50,5
8,9,Race King,PS5,Asia,30,18
10,11,Soccer Stars 2026,PC,Norteamerica,60,14
11,12,CyberQuest,Nintendo Switch,Latinoamerica,50,2
13,14,Race King,Xbox,Asia,30,10
15,16,Soccer Stars 2026,Nintendo Switch,Norteamerica,60,9
17,18,Galactic Combat,Xbox,Europa,40,11
18,19,Race King,PC,Asia,30,4
19,20,Fantasy RPG,Nintendo Switch,Latinoamerica,70,15

Ventas en latinoamerica

In [39]:
mascara = df_ventas['Region'] == "Latinoamerica"
mascara.head()

0     True
1    False
2    False
3    False
4     True
Name: Region, dtype: bool

Aplico la mascara y funciones de ordenamiento

In [47]:
df_ventas[mascara].sort_values(by=["Plataforma", "Unidades_Vendidas"], ascending=False)

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
9,10,Fantasy RPG,Xbox,Latinoamerica,70,40
4,5,Fantasy RPG,PS5,Latinoamerica,70,30
16,17,CyberQuest,PS5,Latinoamerica,50,28
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
14,15,Fantasy RPG,PC,Latinoamerica,70,35
6,7,CyberQuest,PC,Latinoamerica,50,5
19,20,Fantasy RPG,Nintendo Switch,Latinoamerica,70,15
11,12,CyberQuest,Nintendo Switch,Latinoamerica,50,2

Filtro con multilples condiciones

In [ ]:
condicion1 = df_ventas['Unidades_Vendidas'] > 20
condicion2 = df_ventas['Region'] == "Latinoamerica"

df_ventas[condicion1 & condicion2]

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
4,5,Fantasy RPG,PS5,Latinoamerica,70,30
9,10,Fantasy RPG,Xbox,Latinoamerica,70,40
14,15,Fantasy RPG,PC,Latinoamerica,70,35
16,17,CyberQuest,PS5,Latinoamerica,50,28

### C. Filtros Múltiples
Usamos `&` para "Y" (ambas deben cumplirse) y `|` para "O" (al menos una debe cumplirse).
**Importante:** Cada condición debe ir entre paréntesis `()`.

In [ ]:
# Filtrar ventas de PS5 Y que sean de la región 'Latinoamerica'
filtro_combinado = (df_ventas['Plataforma'] == 'PS5') & (df_ventas['Region'] == 'Latinoamerica')
df_ventas[filtro_combinado]

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
4,5,Fantasy RPG,PS5,Latinoamerica,70,30
16,17,CyberQuest,PS5,Latinoamerica,50,28

--- 
## 4. Transformaciones Vectorizadas 
En Pandas, no usamos ciclos `for` o `while` para operar celdas. Hacemos operaciones directas entre columnas.

In [11]:
# Crear una columna calculada directamente
df_ventas['Ingreso_Estimado'] = df_ventas['Precio_Unitario'] * df_ventas['Unidades_Vendidas']
df_ventas.head()

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas,Ingreso_Estimado
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25,1500
1,2,CyberQuest,Xbox,Norteamerica,50,12,600
2,3,Galactic Combat,PC,Europa,40,45,1800
3,4,Race King,Nintendo Switch,Asia,30,8,240
4,5,Fantasy RPG,PS5,Latinoamerica,70,30,2100

### Manipulación de Texto Vectorizado con `.str`
Si queremos limpiar o extraer partes de un texto, usamos los métodos de string nativos de Pandas.

In [52]:
# Ejemplo: Convertir la región a mayúsculas sostenidas de una sola vez
df_ventas['Region_Mayus'] = df_ventas['Region'].str.upper()
df_ventas[['Region', 'Region_Mayus']].head()

          Region   Region_Mayus
0  Latinoamerica  LATINOAMERICA
1   Norteamerica   NORTEAMERICA
2         Europa         EUROPA
3           Asia           ASIA
4  Latinoamerica  LATINOAMERICA

In [ ]:
df_ventas

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas,Region_Mayus
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25,LATINOAMERICA
1,2,CyberQuest,Xbox,Norteamerica,50,12,NORTEAMERICA
2,3,Galactic Combat,PC,Europa,40,45,EUROPA
3,4,Race King,Nintendo Switch,Asia,30,8,ASIA
4,5,Fantasy RPG,PS5,Latinoamerica,70,30,LATINOAMERICA
5,6,Soccer Stars 2026,Xbox,Europa,60,15,EUROPA
6,7,CyberQuest,PC,Latinoamerica,50,5,LATINOAMERICA
7,8,Galactic Combat,Nintendo Switch,Norteamerica,40,22,NORTEAMERICA
8,9,Race King,PS5,Asia,30,18,ASIA
9,10,Fantasy RPG,Xbox,Latinoamerica,70,40,LATINOAMERICA
10,11,Soccer Stars 2026,PC,Norteamerica,60,14,NORTEAMERICA
11,12,CyberQuest,Nintendo Switch,Latinoamerica,50,2,LATINOAMERICA
12,13,Galactic Combat,PS5,Europa,40,50,EUROPA
13,14,Race King,Xbox,Asia,30,10,ASIA
14,15,Fantasy RPG,PC,Latinoamerica,70,35,LATINOAMERICA
15,16,Soccer Stars 2026,Nintendo Switch,Norteamerica,60,9,NORTEAMERICA
16,17,CyberQuest,PS5,Latinoamerica,50,28,LATINOAMERICA
17,18,Galactic Combat,Xbox,Europa,40,11,EUROPA
18,19,Race King,PC,Asia,30,4,ASIA
19,20,Fantasy RPG,Nintendo Switch,Latinoamerica,70,15,LATINOAMERICA

--- 
## 5. Agrupaciones (`groupby`)
El método `groupby` nos permite resumir información por categorías siguiendo la lógica: Dividir -> Aplicar -> Combinar.

In [13]:
# Pregunta: ¿Cuántas unidades totales se vendieron por cada Plataforma?
# Agrupamos por 'Plataforma', seleccionamos 'Unidades_Vendidas' y aplicamos la suma (.sum())
ventas_por_consola = df_ventas.groupby('Plataforma')['Unidades_Vendidas'].sum()
ventas_por_consola

Plataforma
Nintendo Switch     56
PC                 103
PS5                151
Xbox                88
Name: Unidades_Vendidas, dtype: int64

--- 
## 6. Exportar Resultados
Una vez terminado nuestro análisis, podemos guardarlo directamente en un nuevo archivo Excel o CSV.

In [14]:
# Guardamos el resumen anterior en un CSV
ventas_por_consola.to_csv('resumen_ventas_plataformas.csv', header=True)
print("¡Archivo exportado con éxito!")

¡Archivo exportado con éxito!